site_name: Sudheer Reddy G
copyright: Sudheer Reddy G

nav:
    - Home: index.md
    - Getting Started: main/started.md
    - Development:
      - su/versions.md
      - su/releasenotes.md
    - About: about.md

copyright: Copyright &copy; 2023 Sudheer Reddy G
